import express from 'express';
import crypto from 'crypto';
import multer from 'multer';
import { pool, audit } from '../db.js';
import { config } from '../config.js';
import { authMiddleware } from '../middleware/auth.js';
import { putObject, getObject } from '../lib/storage.js';
const router=express.Router();
const allowedTypes=new Set(['application/pdf','image/jpeg','image/png']);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:config.maxFileBytes},fileFilter:(_r,f,cb)=>cb(null,allowedTypes.has(f.mimetype))});
async function access(req,id){const r=await pool.query('SELECT id,user_id FROM expedientes WHERE id=$1',[id]);if(!r.rowCount)return null;return req.user.role==='admin'||Number(r.rows[0].user_id)===Number(req.user.id)?r.rows[0]:false;}
router.post('/upload/:expedienteId',authMiddleware,(req,res)=>upload.single('file')(req,res,async err=>{if(err)return res.status(400).json({message:err.code==='LIMIT_FILE_SIZE'?'Archivo demasiado grande':'Archivo no permitido'});if(!req.file)return res.status(400).json({message:'Archivo requerido'});try{const a=await access(req,req.params.expedienteId);if(a===null)return res.status(404).json({message:'Expediente no encontrado'});if(a===false)return res.status(403).json({message:'No tienes acceso a este expediente'});const ext=req.file.mimetype==='application/pdf'?'.pdf':req.file.mimetype==='image/png'?'.png':'.jpg';const key=`expedientes/${req.params.expedienteId}/${crypto.randomUUID()}${ext}`;await putObject(key,req.file.buffer,req.file.mimetype);const r=await pool.query('INSERT INTO documents (expediente_id,file_name,storage_path,mime_type,size_bytes,uploaded_by) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,file_name,mime_type,size_bytes,created_at',[req.params.expedienteId,req.file.originalname,key,req.file.mimetype,req.file.size,req.user.id]);await audit(req.user.id,'UPLOAD','document',r.rows[0].id,req.ip);res.status(201).json(r.rows[0]);}catch(e){console.error(e);res.status(500).json({message:'No se pudo guardar el documento'});}}));
router.get('/:expedienteId',authMiddleware,async(req,res)=>{const a=await access(req,req.params.expedienteId);if(a===null)return res.status(404).json({message:'Expediente no encontrado'});if(a===false)return res.status(403).json({message:'No tienes acceso a este expediente'});const r=await pool.query('SELECT id,file_name,mime_type,size_bytes,created_at FROM documents WHERE expediente_id=$1 ORDER BY created_at DESC',[req.params.expedienteId]);res.json(r.rows);});
router.get('/:expedienteId/:documentId/download',authMiddleware,async(req,res)=>{const a=await access(req,req.params.expedienteId);if(a===null)return res.status(404).json({message:'Expediente no encontrado'});if(a===false)return res.status(403).json({message:'No tienes acceso a este expediente'});const r=await pool.query('SELECT * FROM documents WHERE id=$1 AND expediente_id=$2',[req.params.documentId,req.params.expedienteId]);if(!r.rowCount)return res.status(404).json({message:'Documento no encontrado'});try{const obj=await getObject(r.rows[0].storage_path);await audit(req.user.id,'DOWNLOAD','document',r.rows[0].id,req.ip);res.setHeader('Content-Type',obj.contentType||r.rows[0].mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(r.rows[0].file_name)}`);obj.stream.pipe(res);}catch{res.status(404).json({message:'Archivo no disponible'});}});
export default router;
