import { useEffect,useState } from 'react';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const empty={tramite:'Nuevo ingreso',nombre:'',curp:'',rfc:'',correo:'',telefono:'',universidad:'',cedula:'',profesion:'Contador Público',observaciones:''};
function App(){const [token,setToken]=useState(localStorage.getItem('ccpt-token')||'');const [user,setUser]=useState(JSON.parse(localStorage.getItem('ccpt-user')||'null'));const [login,setLogin]=useState({email:'',password:''});const [rows,setRows]=useState([]);const [selected,setSelected]=useState(null);const [docs,setDocs]=useState([]);const [form,setForm]=useState(empty);const [msg,setMsg]=useState('');
const headers={Authorization:`Bearer ${token}`};
useEffect(()=>{if(token)load();},[token]); async function load(){const r=await fetch(`${API}/expedientes`,{headers});if(r.ok)setRows(await r.json());else logout();}
async function submitLogin(e){e.preventDefault();const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});const d=await r.json();if(!r.ok)return setMsg(d.message);localStorage.setItem('ccpt-token',d.token);localStorage.setItem('ccpt-user',JSON.stringify(d.user));setToken(d.token);setUser(d.user);setMsg('');}
function logout(){localStorage.clear();setToken('');setUser(null);setRows([]);setSelected(null);}
async function save(e){e.preventDefault();const r=await fetch(`${API}/expedientes`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)return setMsg(d.message);setMsg('Expediente guardado');setForm(empty);load();setSelected(d);}
async function choose(x){setSelected(x);setForm({...empty,...x});const r=await fetch(`${API}/documents/${x.id}`,{headers});setDocs(r.ok?await r.json():[]);}
async function upload(e){const file=e.target.files?.[0];if(!file||!selected)return;const body=new FormData();body.append('file',file);const r=await fetch(`${API}/documents/upload/${selected.id}`,{method:'POST',headers,body});const d=await r.json();setMsg(r.ok?'Documento cargado':d.message);if(r.ok)choose(selected);e.target.value='';}
async function download(d){const r=await fetch(`${API}/documents/${selected.id}/${d.id}/download`,{headers});if(!r.ok)return setMsg('No se pudo descargar');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=d.file_name;a.click();URL.revokeObjectURL(a.href);}
if(!user)return <main className="login"><form onSubmit={submitLogin}><h1>CCPT Expediente Digital</h1><label>Correo<input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Contraseña<input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button>Iniciar sesión</button><p className="message">{msg}</p></form></main>;
return <><header><div><h1>CCPT | Expediente Digital</h1><small>{user.name} · {user.role}</small></div><button onClick={logout}>Cerrar sesión</button></header><main className="layout"><section className="panel"><div className="toolbar"><h2>{user.role==='admin'?'Expedientes institucionales':'Mi expediente'}</h2><button onClick={()=>{setSelected(null);setForm(empty)}}>Nuevo</button></div>{msg&&<p className="message">{msg}</p>}<table><thead><tr><th>Folio</th><th>Nombre</th><th>Trámite</th><th>Estatus</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} onClick={()=>choose(x)}><td>{x.folio}</td><td>{x.nombre}</td><td>{x.tramite}</td><td>{x.estatus}</td></tr>)}</tbody></table></section><section className="panel"><h2>{selected?'Detalle / documentos':'Capturar expediente'}</h2><form onSubmit={save} className="formgrid">{['nombre','curp','rfc','correo','telefono','universidad','cedula','profesion','tramite','observaciones'].map(k=><label key={k}>{k}<input value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button>Guardar expediente</button></form>{selected&&<><h3>Documentos del expediente</h3><label className="upload">Cargar documento<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={upload}/></label><ul>{docs.map(d=><li key={d.id}><button type="button" onClick={()=>download(d)}>{d.file_name}</button></li>)}</ul></>}</section></main></>}
export default App;
